language: php

services:
  - redis-server

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - vendor/bin/atoum -d tests
