name: Continuous Integration
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: [ '7.4', '8.0', '8.1' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug2
      - name: Install dependencies
        run: composer install --dev
      - name: Unit tests
        run: |-
          vendor/bin/atoum -d tests
          vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --verbose